#!/bin/sh
ARGS="$@"

DIRNAME=`pwd`/`dirname "$0"`


. $DIRNAME/dldialog_funcs

dldialog_start $ARGS||exit 10

result=$($DLDIALOG <<EOF
dialog "All GUI Elements" -width 100 {
#      button "Here you see a png Image in a button \"\" -sign -image \"\"" -sign -image "$DIRNAME/ani.gif";
      button "Here (in qt-mode) you see a png Image in a button \"\" -sign -image \"\"" -sign -image "$DIRNAME/pnglogo.png";
      row -width 100 {
      image "$DIRNAME/DLD.xpm";
	 row "The Lists" -width 100 {
	    lv="2 3";
            #li="2";
	    list "A &List" -width 100 -font Times -size huge -var lv  {
	       listitem "1. Listitem" -image "$DIRNAME/tick.xpm" -var li -set 1;
	       listitem "2. Listitem" -image "$DIRNAME/tick.xpm" -var li -set 2 -exit;
	       listitem "3. Listitem" -var li -set 3 -image "$DIRNAME/weiter.xpm";
	       listitem "4. Listitem" -font Courier -fg "#bf0f38" -var li -set 4;
	       listitem "5. Listitem" -font Italic -size mini -fg darkgreen -var li -set 5;
	       listitem "6. Listitem"-font Roman -size mini  -var li -set 6;
	    }
	    
	    text "  "; //Spacer
	    
            checkvar="1 3";
	    checklist "A &Checklist" -var checkvar {
	       checkbutton "&1. checkbutton" -var cb -set 1;
	       checkbutton "&2. checkbutton" -var cb -set 2 -exit;
	    }
	    
	    text "  "; //Spacer
	    
	    radiovar="3";

	    radiolist "A &Radiolist" -var radiovar {
	       radiobutton "&1. radiobutton" -var rb -set 1;
	       radiobutton "&2. radiobutton" -var rb -set 2 -exit;
	    }
	 }
     }
      
         STATIC_GAUGE="50";
         text "Gauges";
         row { 
	   gauge  -exec "echo 0; sleep 1; echo 50; sleep 1;""for i in \`seq 1 100\`;do echo \$i;sleep 0;done";
           gauge  -var STATIC_GAUGE;
	 }
      row {
         text "ComboBox:";
	 cobo="2";
	 combobox -var cobo  {
	   comboitem "Item 1" -var ci -set "1"; 
	   comboitem "Item 2" -var ci -set "2"; 
	   comboitem "Item 3" -var ci -set "3" -exit; 
	 }
	 
	 text " Input:"; 
	 iv="bla bla bla";
	 input -var iv -width 100;
      }	 
      
      row -width 100 { 
	 text "Passwd:"; 
	 iv="bla bla bla";
	 input -var iv -passwd -length 10;

	 text " Numeric:"; 
	 ivn="1234567890";
	 input -var ivn -numeric -length 10 -exit;
	 
	 text " IP:"; 
	 ivi="123.123.123.123";
	 input -var ivi -ip;
      }
   
      text "ÄÖÜaöüß"; //Spacer
      
      row -width 100 {
	 button "&Not OK - output is scrambled"  -font OldEnglish -size small -var OK -set 0 -exit;
	 button "&Source"  -font Serif -size big -exec "$DLDIALOG <<EOF
	   dialog \"Source\" -width 100 -height 100 {
	         text \"The source of the file:\n$0\" -font Courier;
		 textbox \"A TextBox\" -font Courier -file \"$0\" -width 100 ;
		 text \"\"; //Spacer
		 button \"OK\" -exit;
	   }
EOF";
	 button "&OK - seen all" -image "$DIRNAME/tick.xpm" -font Serif -fg "#ff0000" -var OK -set 1 -exit;
      }
#   }
}
EOF
)

eval "$result"

dldialog_stop

echo $result

echo "li muesste eigentlich 1 sein, ist aber leer."
echo li = $li
