#!/bin/sh
ARGS="$@"

DIRNAME=`pwd`/`dirname "$0"`

. $DIRNAME/dldialog_funcs

dldialog_start $ARGS||exit 10

result=$($DLDIALOG <<EOF
dialog "All GUI Elements" -width 100 {
      row -width 100 -height 100 {
      button "A button" -image "$DIRNAME/DLD.xpm" -sign;
      image "$DIRNAME/pnglogo.png";
       col "Column" -width 100 {
	 row -width 100 {
	 text "A Row";
	    button "Button" " 1 20%" -image "$DIRNAME/DLD-start.xpm" -width 20;
	    button "Button" " 1 30%" -image "$DIRNAME/DLD-start.xpm" -width 30;
	    button "Button" " 2 50%" -image "$DIRNAME/DLD-start.xpm" -width 50;
	 }
      
	 row "The Lists" -width 100 {
	    lv="2 3";
            #li="2";
	    list "A &List" -width 100 -var lv  -multi {
	       listitem "1. Listitem" -var li -set 1;
	       listitem "2. Listitem" -var li -set 2 -exit;
	       listitem "3. Listitem" -var li -set 3;
	    }
	    
	    text "  "; //Spacer
	    
            checkvar="1 3";
	    checklist "A &Checklist" -var checkvar {
	       checkbutton "&1. checkbutton" -var cb -set 1;
	       checkbutton "&2. checkbutton" -var cb -set 2 -exit;
	       checkbutton "&3. checkbutton" -var cb -set 3;
	    }
	    
	    text "  "; //Spacer
	    
	    radiovar="3";

	    radiolist "A &Radiolist" -var radiovar {
	       radiobutton "&1. radiobutton" -var rb -set 1;
	       radiobutton "&2. radiobutton" -var rb -set 2 -exit;
	       radiobutton "&3. radiobutton" -var rb -set 3;
	    }
	 }
     }}
      
         STATIC_GAUGE="50";
         text "Gauges";
         row { 
	   gauge  -exec "echo 0; sleep 1; echo 50; sleep 1;""for i in \`seq 1 100\`;do echo \$i;sleep 0;done";
           gauge  -var STATIC_GAUGE;
	 }
      text ""; //Spacer
      row {
         text "ComboBox:";
	 cobo="2";
	 combobox -var cobo  {
	   comboitem "Item 1" -var ci -set "1"; 
	   comboitem "Item 2" -var ci -set "2"; 
	   comboitem "Item 3" -var ci -set "3" -exit; 
	 }
	 
	 text " Input:"; 
	 iv="bla bla bla";
	 input -var iv -width 100;
      }	 
      text ""; //Spacer
      
      row -width 100 { 
	 text "Passwd:"; 
	 iv="bla bla bla";
	 input -var iv -passwd -length 10;

	 text " Numeric:"; 
	 ivn="1234567890";
	 input -var ivn -numeric -length 10 -exit;
	 
	 text " IP:"; 
	 ivi="123.123.123.123";
	 input -var ivi -ip;
      }
   
      text ""; //Spacer
      
      row -width 100 {
	 button "&Not OK - output is scrambled" -var OK -set 0 -exit;
	 button "&Source" -exec "$DLDIALOG <<EOF
	   dialog \"Source\" -width 100 -height 100 {
	         text \"The source of the file:\n$0\";		 
		 textbox \"A TextBox\" -file \"$0\" -width 100 ;
		 text \"\"; //Spacer
		 button \"OK\" -exit;
	   }
EOF";
	 button "&OK - seen all" -var OK -set 1 -exit;
      }
#   }
}
EOF
)

eval "$result"
echo $result
echo LV = $lv

if [ "$OK" = "1" ]; 
then 
   echo "All right"
   exit 0;
else
   echo "Output is scrambled ... for best results use rxvt or linux console"
   exit 1;
fi

