/* Automatically generated by po2tbl.sed from dldialog.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"Usage: ", 2},
  {"\
 [OPTIONS]\n\
\n\
OPTIONS:\n\
\t-f, --file \tread input from file, rather than from stdin\n", 3},
  {"\t-q, --qt \tstart with Qt (X11) interface\n", 4},
  {"\t-t, --tv \tstart with tvision (terminal) interface\n", 5},
  {"\
\t-T, --title \tsets the window title to the next argument\n\
\t-p, --parse \tparse only to check input\n\
\t-b, --start \tstart dldialog server\n\
\t-e, --stop \tstop dldialog server\n\
\t-w, --wait \twait for dldialog server to end\n\
\t-d, --debug \tdisplays debugging output\n\
\t-v, --version \tdisplay version information and exit\n\
\t-h, --help \tdisplay this help and exit\n\
\n", 6},
  {" tried!", 7},
  {"Sending start", 8},
  {"Waiting for ok", 9},
  {"Sending stop", 10},
  {"Sending client {", 11},
  {"Sending }", 12},
  {"Getting output pipe", 13},
  {" is no output pipe", 14},
  {"Opening output pipe ", 15},
  {"Reading output pipe ", 16},
  {"Deleting output pipe ", 17},
  {"dldialog version ", 18},
  {"\
\tby Harald Hoyer (HarryH@Royal.Net)\n\
\tfor delix Computer GmbH (http://www.delix.de)\n", 19},
  {"DLD_PRELOAD not specified!", 20},
  {"Another mode was already selected!", 21},
  {"QT support not compiled in!", 22},
  {"TVision support not compiled in!", 23},
  {"Try `", 24},
  {" could not be loaded", 25},
  {"SPACE selects - TAB to move -", 26},
};

int _msg_tbl_length = 26;
